### ISSUE TITLE
numpy installation is missing during build_ngtf.py and causes build to crash.

### ISSUE THREAD

**Issue by ashahba** [tensorflow/ngraph-bridge#384]
While running `build_ngtf.py` on a fresh virtualenv the build failed due to `numpy` not being found.
Once I manually installed it I resume with the rest of the build.

**Comment by ashahba** [comment]
This one also should be a nice first issue during ramp up.

**Comment by adk9** [comment]
`build_ngtf.py` is supposed to pip install `numpy`. I cannot reproduce this issue; can you please include the logs of when you see this error?

**Comment by ashahba** [comment]
This was reported back when I just started working on the repo and possibly a user error 🙂
